services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: journal_mastra
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
